/**
 * glossary-data.js - AI-industry glossary. Terms referenced with
 * <span class="term" data-term="...">...</span>
 */
window.GLOSSARY = {
  "Closed-weight": "AI models whose trained parameters (weights) are kept private and accessed only via commercial APIs or productized apps. Examples: GPT-5.4, Claude Opus 4.6, Gemini 3.1 Pro.",
  "Open-weight": "AI models whose trained parameters are published for download — anyone can self-host, fine-tune, and redistribute. Not the same as 'open source' (which also requires training data + code). Examples: Llama 4, Mistral, Qwen 3.5, DeepSeek.",
  "Open source (strict)": "OSI-sense open source requires release of training data, training code, AND weights. Very few models clear this bar; AI2's OLMo is one.",
  "Capability Rent": "The premium a closed-weight lab charges for being at the frontier. If a model automates a $150k engineer's output, $200/month per seat captures only a fraction of the value — that fraction is the rent.",
  "Commoditize Your Complements": "Joel Spolsky's strategy: make the thing adjacent to your business free/cheap to drive demand for your business. Meta open-sources Llama to commoditize the model layer and protect its ad business.",
  "MoE": "Mixture of Experts. Sparse architecture that routes each token through only a subset of the model's 'expert' sub-networks. 2026's dominant architecture — lets total parameter count scale while active compute stays manageable.",
  "RLHF": "Reinforcement Learning from Human Feedback. Training technique for aligning models to human preferences. Closed labs have proprietary RLHF datasets that open-weight labs cannot easily replicate.",
  "Agentic AI": "Models that autonomously take multi-step actions (tool use, code execution, browsing) rather than just answering a single turn. The 2026 frontier — Claude Cowork, Kimi K2.6 (13-hour autonomous refactoring), Zhipu GLM-5.1 (8hr sessions).",
  "MCP": "Model Context Protocol. Anthropic-donated open standard for connecting models to tools and data sources. Crossed 97M installs in March 2026. Now stewarded by the Linux Foundation's Agentic AI Foundation.",
  "SWE-bench": "Industry benchmark measuring a model's ability to resolve real software-engineering issues. Claude Mythos 5 scores 93.9% SWE-bench Verified.",
  "GDPval": "Benchmark covering 44 real-world occupations. GPT-5.4 set a record 83% in March 2026.",
  "GPQA Diamond": "Graduate-level science questions designed to be 'Google-proof.' Gemini 3.1 Pro leads at 94.3%; Claude Mythos 5 at 94.6%.",
  "CoWoS": "Chip-on-Wafer-on-Substrate. TSMC's advanced-packaging technology that integrates logic dies with HBM stacks on a silicon interposer. The single binding constraint on AI chip production — sold out through mid-2026.",
  "HBM": "High-Bandwidth Memory. Vertically stacked DRAM mounted directly on AI accelerator packages. SK Hynix ~62% market share. Entire 2026 HBM capacity already allocated.",
  "HBM4": "Next-gen high-bandwidth memory with 2.8 TB/s bandwidth. Mass production ramp in 2026; volume supplier to NVIDIA Blackwell Ultra and Rubin platforms.",
  "High-NA EUV": "ASML's next-generation Extreme Ultraviolet lithography machines (~$380M each vs. $180–200M standard). Required for Intel 18A and the sub-1.4nm logic nodes beyond 2026.",
  "ASIC": "Application-Specific Integrated Circuit. Custom silicon designed for a single workload — cheaper and more efficient than general-purpose GPUs at steady-state inference. Google TPU, AWS Trainium, Meta MTIA.",
  "TPU": "Google's Tensor Processing Unit — its proprietary AI accelerator. Vertically integrated into GCP. Anthropic committed to multi-GW of next-gen TPU capacity starting 2027.",
  "Trainium": "AWS's custom AI training chip. Anthropic secured 2GW of Trainium compute under its expanded Amazon partnership.",
  "Blackwell": "NVIDIA's current-gen data-center GPU architecture (B100/B200, and Blackwell Ultra). Succeeded by Vera Rubin at the 2026 frontier.",
  "Ascend 950PR": "Huawei's latest AI accelerator, expected to host DeepSeek V4. Demonstrates Chinese hardware independence from U.S.-restricted NVIDIA GPUs.",
  "ARR": "Annualized Recurring Revenue. OpenAI ~$25B ARR (April 2026), Anthropic ~$30B ARR — both growing 200%+ YoY.",
  "Pre-IPO Secondary": "A private-company share transaction between existing shareholders (employees, early VCs) and new buyers, brokered via platforms like Hiive and Forge. Accredited investors only.",
  "Interval Fund": "A closed-end fund that offers redemption only at set intervals (typically quarterly). Example: ARK Venture Fund (ARKVX). Not a liquid instrument.",
  "Closed-End Fund": "An exchange-traded fund with a fixed share count — price can trade at a premium or discount to NAV. Destiny Tech100 (DXYZ) typically trades at a persistent NAV premium.",
  "NAV Premium": "The percentage by which a CEF's share price exceeds its underlying net asset value. Indicates excess demand for access to hard-to-reach private holdings.",
  "Stargate": "The $500B OpenAI/SoftBank/Oracle data-center buildout announced in 2025. Significantly stalled by Q3-Q4 2025 as new DC deals fell >40%.",
  "Capability Convergence": "The narrowing capability gap between open-weight and closed-weight models — now down to single-digit percentage points on most benchmarks.",
  "Project Glasswing": "Anthropic's restricted-deployment program for Claude Mythos 5 (~50 organizations only), citing cybersecurity misuse potential. First frontier model publicly withheld for capability reasons.",
  "Vera Rubin": "NVIDIA's next-generation data-center GPU platform following Blackwell Ultra, targeting frontier training workloads beyond 2026.",
  "PJM": "The U.S. regional transmission organization serving 13 eastern states + DC. Projects a ~6GW reliability shortfall by 2027 driven by AI data-center load.",
  "SMR": "Small Modular Reactor. Compact nuclear reactor designs (50–300 MW) targeting AI data-center power needs. OKLO and NNE are speculative pure plays.",
  "Ratepayer Protection Pledge": "March 2026 White-House-coordinated pledge by major data center developers to cover the full cost of new electric generation. Voluntary and unenforceable.",
};
