"""
build_report_context.py — Extract GS_AI_Coverage_Report.docx into js/report-context.js.

Outputs a module that sets window.REPORT_CONTEXT to the full report text
(paragraphs + tables) — used as Gemini's system instruction.

Usage:  python build_report_context.py
"""
import json
import os
import sys

try:
    from docx import Document
except ImportError:
    print("python-docx not installed. Run: python -m pip install python-docx")
    sys.exit(1)

HERE = os.path.dirname(os.path.abspath(__file__))
DOCX = os.path.join(HERE, "GS_AI_Coverage_Report_v2.docx")
OUT = os.path.join(HERE, "js", "report-context.js")

doc = Document(DOCX)

parts = []

for p in doc.paragraphs:
    t = p.text.strip()
    if not t:
        continue
    style = (p.style.name or "").lower() if p.style else ""
    if style.startswith("heading"):
        # Preserve heading hierarchy as markdown-like ##
        level = style.replace("heading ", "").strip() or "1"
        try:
            hashes = "#" * int(level)
        except ValueError:
            hashes = "#"
        parts.append(f"\n{hashes} {t}\n")
    else:
        parts.append(t)

for ti, t in enumerate(doc.tables):
    parts.append(f"\n### Table {ti + 1}\n")
    for row in t.rows:
        cells = [c.text.strip().replace("\n", " ") for c in row.cells]
        parts.append("| " + " | ".join(cells) + " |")
    parts.append("")

body = "\n".join(parts).strip()

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", encoding="utf-8") as f:
    f.write("// Auto-generated by build_report_context.py — do not edit by hand.\n")
    f.write("window.REPORT_CONTEXT = ")
    f.write(json.dumps(body, ensure_ascii=False))
    f.write(";\n")

print(f"Wrote {OUT} ({len(body):,} chars)")
