"""
load_env.py — Bridge .env.local to the browser.

Reads .env.local and writes js/gemini-key.js so index.html can pick up
the Gemini API key at runtime. Both .env.local and js/gemini-key.js are
gitignored — the key never enters version control.

Usage:  python load_env.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ENV_PATH = os.path.join(HERE, ".env.local")
OUT_PATH = os.path.join(HERE, "js", "gemini-key.js")


def parse_env(path):
    values = {}
    if not os.path.exists(path):
        return values
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                continue
            k, v = line.split("=", 1)
            values[k.strip()] = v.strip().strip('"').strip("'")
    return values


def main():
    env = parse_env(ENV_PATH)
    key = env.get("GEMINI_API_KEY", "").strip()
    if not key:
        print("ERROR: GEMINI_API_KEY is empty in .env.local")
        print("  Paste your key into .env.local and re-run this script.")
        sys.exit(1)

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    # JSON-escape the key so any special characters survive JS parsing.
    safe = key.replace("\\", "\\\\").replace('"', '\\"')
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by load_env.py from .env.local — do not edit by hand.\n")
        f.write("// This file is gitignored.\n")
        f.write(f'window.GEMINI_API_KEY = "{safe}";\n')

    print(f"Wrote {OUT_PATH}")
    print(f"Key length: {len(key)} chars (first 4: {key[:4]}…)")


if __name__ == "__main__":
    main()
